-- Jogo do Impostor — banco de palavras
-- 200 palavras, 10 categorias, 20 por categoria.
--
-- REGRAS DA LISTA (garantidas por check em `words`):
--
-- 1. UMA palavra, sem espaço. O jogo é dar dicas SOBRE a palavra; uma frase como
--    "Entrevista de Emprego" já é a própria dica, e ainda estoura o card.
-- 2. Concreta e conhecida por criança de 9 anos. Se precisa explicar o que é, não
--    entra: quem não conhece a palavra não consegue dar dica nem desconfiar de
--    ninguém, e acaba parecendo o impostor sem ser.
--
-- A categoria não é decoração: os 3 distratores da Última Chance são sorteados da
-- MESMA categoria da palavra secreta. Menos de 4 palavras numa categoria tornaria
-- o palpite do impostor um sorteio óbvio.

insert into words (text, category) values
  -- 1. Lugares & Ambientes
  ('Praia',          'LUGARES'),
  ('Escola',         'LUGARES'),
  ('Hospital',       'LUGARES'),
  ('Circo',          'LUGARES'),
  ('Zoológico',      'LUGARES'),
  ('Cinema',         'LUGARES'),
  ('Padaria',        'LUGARES'),
  ('Mercado',        'LUGARES'),
  ('Praça',          'LUGARES'),
  ('Piscina',        'LUGARES'),
  ('Fazenda',        'LUGARES'),
  ('Floresta',       'LUGARES'),
  ('Castelo',        'LUGARES'),
  ('Aeroporto',      'LUGARES'),
  ('Museu',          'LUGARES'),
  ('Biblioteca',     'LUGARES'),
  ('Farmácia',       'LUGARES'),
  ('Sorveteria',     'LUGARES'),
  ('Deserto',        'LUGARES'),
  ('Igreja',         'LUGARES'),

  -- 2. Comidas & Bebidas
  ('Pizza',          'COMIDAS'),
  ('Sorvete',        'COMIDAS'),
  ('Chocolate',      'COMIDAS'),
  ('Brigadeiro',     'COMIDAS'),
  ('Pipoca',         'COMIDAS'),
  ('Hambúrguer',     'COMIDAS'),
  ('Bolo',           'COMIDAS'),
  ('Banana',         'COMIDAS'),
  ('Melancia',       'COMIDAS'),
  ('Morango',        'COMIDAS'),
  ('Macarrão',       'COMIDAS'),
  ('Queijo',         'COMIDAS'),
  ('Arroz',          'COMIDAS'),
  ('Feijão',         'COMIDAS'),
  ('Ovo',            'COMIDAS'),
  ('Pastel',         'COMIDAS'),
  ('Biscoito',       'COMIDAS'),
  ('Sanduíche',      'COMIDAS'),
  ('Suco',           'COMIDAS'),
  ('Bombom',         'COMIDAS'),

  -- 3. Animais
  ('Cachorro',       'ANIMAIS'),
  ('Gato',           'ANIMAIS'),
  ('Elefante',       'ANIMAIS'),
  ('Girafa',         'ANIMAIS'),
  ('Leão',           'ANIMAIS'),
  ('Macaco',         'ANIMAIS'),
  ('Cavalo',         'ANIMAIS'),
  ('Vaca',           'ANIMAIS'),
  ('Galinha',        'ANIMAIS'),
  ('Porco',          'ANIMAIS'),
  ('Pinguim',        'ANIMAIS'),
  ('Tartaruga',      'ANIMAIS'),
  ('Cobra',          'ANIMAIS'),
  ('Aranha',         'ANIMAIS'),
  ('Borboleta',      'ANIMAIS'),
  ('Tubarão',        'ANIMAIS'),
  ('Golfinho',       'ANIMAIS'),
  ('Coelho',         'ANIMAIS'),
  ('Urso',           'ANIMAIS'),
  ('Papagaio',       'ANIMAIS'),

  -- 4. Profissões
  ('Médico',         'PROFISSOES'),
  ('Professor',      'PROFISSOES'),
  ('Bombeiro',       'PROFISSOES'),
  ('Policial',       'PROFISSOES'),
  ('Dentista',       'PROFISSOES'),
  ('Padeiro',        'PROFISSOES'),
  ('Cozinheiro',     'PROFISSOES'),
  ('Motorista',      'PROFISSOES'),
  ('Piloto',         'PROFISSOES'),
  ('Cantor',         'PROFISSOES'),
  ('Palhaço',        'PROFISSOES'),
  ('Mágico',         'PROFISSOES'),
  ('Pintor',         'PROFISSOES'),
  ('Jardineiro',     'PROFISSOES'),
  ('Veterinário',    'PROFISSOES'),
  ('Astronauta',     'PROFISSOES'),
  ('Carteiro',       'PROFISSOES'),
  ('Pescador',       'PROFISSOES'),
  ('Enfermeiro',     'PROFISSOES'),
  ('Cabeleireiro',   'PROFISSOES'),

  -- 5. Objetos do Cotidiano
  ('Cadeira',        'OBJETOS'),
  ('Mesa',           'OBJETOS'),
  ('Cama',           'OBJETOS'),
  ('Travesseiro',    'OBJETOS'),
  ('Espelho',        'OBJETOS'),
  ('Chuveiro',       'OBJETOS'),
  ('Toalha',         'OBJETOS'),
  ('Tesoura',        'OBJETOS'),
  ('Lápis',          'OBJETOS'),
  ('Caderno',        'OBJETOS'),
  ('Mochila',        'OBJETOS'),
  ('Relógio',        'OBJETOS'),
  ('Chave',          'OBJETOS'),
  ('Vassoura',       'OBJETOS'),
  ('Panela',         'OBJETOS'),
  ('Garfo',          'OBJETOS'),
  ('Copo',           'OBJETOS'),
  ('Sabonete',       'OBJETOS'),
  ('Balde',          'OBJETOS'),
  ('Cobertor',       'OBJETOS'),

  -- 6. Tech & Geek
  ('Celular',        'TECH'),
  ('Computador',     'TECH'),
  ('Televisão',      'TECH'),
  ('Tablet',         'TECH'),
  ('Carregador',     'TECH'),
  ('Teclado',        'TECH'),
  ('Mouse',          'TECH'),
  ('Câmera',         'TECH'),
  ('Videogame',      'TECH'),
  ('Controle',       'TECH'),
  ('Robô',           'TECH'),
  ('Drone',          'TECH'),
  ('Impressora',     'TECH'),
  ('Internet',       'TECH'),
  ('Senha',          'TECH'),
  ('Emoji',          'TECH'),
  ('Selfie',         'TECH'),
  ('Youtube',        'TECH'),
  ('Wifi',           'TECH'),
  ('Fone',           'TECH'),

  -- 7. Esportes & Lazer
  ('Futebol',        'ESPORTES'),
  ('Vôlei',          'ESPORTES'),
  ('Basquete',       'ESPORTES'),
  ('Natação',        'ESPORTES'),
  ('Skate',          'ESPORTES'),
  ('Bicicleta',      'ESPORTES'),
  ('Pipa',           'ESPORTES'),
  ('Corrida',        'ESPORTES'),
  ('Dança',          'ESPORTES'),
  ('Judô',           'ESPORTES'),
  ('Surfe',          'ESPORTES'),
  ('Boliche',        'ESPORTES'),
  ('Xadrez',         'ESPORTES'),
  ('Ginástica',      'ESPORTES'),
  ('Handebol',       'ESPORTES'),
  ('Patinete',       'ESPORTES'),
  ('Cambalhota',     'ESPORTES'),
  ('Trampolim',      'ESPORTES'),
  ('Amarelinha',     'ESPORTES'),
  ('Queimada',       'ESPORTES'),

  -- 8. Cultura Pop
  ('Batman',         'CULTURA_POP'),
  ('Pokémon',        'CULTURA_POP'),
  ('Minecraft',      'CULTURA_POP'),
  ('Roblox',         'CULTURA_POP'),
  ('Naruto',         'CULTURA_POP'),
  ('Frozen',         'CULTURA_POP'),
  ('Mario',          'CULTURA_POP'),
  ('Sonic',          'CULTURA_POP'),
  ('Shrek',          'CULTURA_POP'),
  ('Simpsons',       'CULTURA_POP'),
  ('Barbie',         'CULTURA_POP'),
  ('Hulk',           'CULTURA_POP'),
  ('Rapunzel',       'CULTURA_POP'),
  ('Cinderela',      'CULTURA_POP'),
  ('Pikachu',        'CULTURA_POP'),
  ('Goku',           'CULTURA_POP'),
  ('Mickey',         'CULTURA_POP'),
  ('Superman',       'CULTURA_POP'),
  ('Moana',          'CULTURA_POP'),
  ('Stitch',         'CULTURA_POP'),

  -- 9. Transportes & Viagem
  ('Carro',          'TRANSPORTES'),
  ('Ônibus',         'TRANSPORTES'),
  ('Avião',          'TRANSPORTES'),
  ('Trem',           'TRANSPORTES'),
  ('Barco',          'TRANSPORTES'),
  ('Moto',           'TRANSPORTES'),
  ('Caminhão',       'TRANSPORTES'),
  ('Helicóptero',    'TRANSPORTES'),
  ('Foguete',        'TRANSPORTES'),
  ('Metrô',          'TRANSPORTES'),
  ('Navio',          'TRANSPORTES'),
  ('Ambulância',     'TRANSPORTES'),
  ('Submarino',      'TRANSPORTES'),
  ('Balão',          'TRANSPORTES'),
  ('Táxi',           'TRANSPORTES'),
  ('Trator',         'TRANSPORTES'),
  ('Carroça',        'TRANSPORTES'),
  ('Bonde',          'TRANSPORTES'),
  ('Caminhonete',    'TRANSPORTES'),
  ('Canoa',          'TRANSPORTES'),

  -- 10. Eventos & Situações
  ('Aniversário',    'EVENTOS'),
  ('Natal',          'EVENTOS'),
  ('Casamento',      'EVENTOS'),
  ('Carnaval',       'EVENTOS'),
  ('Páscoa',         'EVENTOS'),
  ('Férias',         'EVENTOS'),
  ('Recreio',        'EVENTOS'),
  ('Acampamento',    'EVENTOS'),
  ('Festa',          'EVENTOS'),
  ('Halloween',      'EVENTOS'),
  ('Formatura',      'EVENTOS'),
  ('Piquenique',     'EVENTOS'),
  ('Desfile',        'EVENTOS'),
  ('Show',           'EVENTOS'),
  ('Mudança',        'EVENTOS'),
  ('Pescaria',       'EVENTOS'),
  ('Churrasco',      'EVENTOS'),
  ('Aula',           'EVENTOS'),
  ('Prova',          'EVENTOS'),
  ('Passeio',        'EVENTOS');
